// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-b5vwm8W-MFDiAQf4rlBsyQnHLDNftMg',
    appId: '1:656380118813:web:8591875e9a69caa72743f4',
    messagingSenderId: '656380118813',
    projectId: 'omnistarr-cg',
    authDomain: 'omnistarr-cg.firebaseapp.com',
    storageBucket: 'omnistarr-cg.firebasestorage.app',
    measurementId: 'G-JG5YP29XPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPG_qWpmaxyJiTPgwnTYsIjeJZqPFNE2o',
    appId: '1:656380118813:android:b232c7780692c8ab2743f4',
    messagingSenderId: '656380118813',
    projectId: 'omnistarr-cg',
    storageBucket: 'omnistarr-cg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCer8HvjyPAiGotghNEbg84rBZtv5vNCOE',
    appId: '1:656380118813:ios:1a976522eb779f102743f4',
    messagingSenderId: '656380118813',
    projectId: 'omnistarr-cg',
    storageBucket: 'omnistarr-cg.firebasestorage.app',
    iosClientId: '656380118813-1uas6a26s8ckppd1ua38cik8fndvi0mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFlutterFirebaseWebrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCer8HvjyPAiGotghNEbg84rBZtv5vNCOE',
    appId: '1:656380118813:ios:1a976522eb779f102743f4',
    messagingSenderId: '656380118813',
    projectId: 'omnistarr-cg',
    storageBucket: 'omnistarr-cg.firebasestorage.app',
    iosClientId: '656380118813-1uas6a26s8ckppd1ua38cik8fndvi0mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFlutterFirebaseWebrtc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-b5vwm8W-MFDiAQf4rlBsyQnHLDNftMg',
    appId: '1:656380118813:web:dbc98c457b22f32f2743f4',
    messagingSenderId: '656380118813',
    projectId: 'omnistarr-cg',
    authDomain: 'omnistarr-cg.firebaseapp.com',
    storageBucket: 'omnistarr-cg.firebasestorage.app',
    measurementId: 'G-E7MYVKV8W3',
  );
}
