// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeUS51IXqUWuyokg85T4lVPTZLmkP-7aU',
    appId: '1:362147646086:web:c143e935d2a479ab115f07',
    messagingSenderId: '362147646086',
    projectId: 'videocallingdemo-8e921',
    authDomain: 'videocallingdemo-8e921.firebaseapp.com',
    storageBucket: 'videocallingdemo-8e921.firebasestorage.app',
    measurementId: 'G-D0Q40C7VVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfM9CFM-C5YS7WtB85Gjx0yjP2fFRS00s',
    appId: '1:362147646086:android:4032123005e42eec115f07',
    messagingSenderId: '362147646086',
    projectId: 'videocallingdemo-8e921',
    storageBucket: 'videocallingdemo-8e921.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtAnaPPFQLr7tBoc2ZvGQloTOM6SbcPDU',
    appId: '1:362147646086:ios:f1fa649684ced6f3115f07',
    messagingSenderId: '362147646086',
    projectId: 'videocallingdemo-8e921',
    storageBucket: 'videocallingdemo-8e921.firebasestorage.app',
    iosBundleId: 'com.example.newFlutterFirebaseWebrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtAnaPPFQLr7tBoc2ZvGQloTOM6SbcPDU',
    appId: '1:362147646086:ios:f1fa649684ced6f3115f07',
    messagingSenderId: '362147646086',
    projectId: 'videocallingdemo-8e921',
    storageBucket: 'videocallingdemo-8e921.firebasestorage.app',
    iosBundleId: 'com.example.newFlutterFirebaseWebrtc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeUS51IXqUWuyokg85T4lVPTZLmkP-7aU',
    appId: '1:362147646086:web:2b033e30a9a1054a115f07',
    messagingSenderId: '362147646086',
    projectId: 'videocallingdemo-8e921',
    authDomain: 'videocallingdemo-8e921.firebaseapp.com',
    storageBucket: 'videocallingdemo-8e921.firebasestorage.app',
    measurementId: 'G-SZCLYSQ58F',
  );
}
