// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1UuXuOcHZZrraPIVuZwi_9cCEtPLanIk',
    appId: '1:365129109511:web:69c7825e84c4ac46299aa2',
    messagingSenderId: '365129109511',
    projectId: 'demo1-527bc',
    authDomain: 'demo1-527bc.firebaseapp.com',
    databaseURL: 'https://demo1-527bc-default-rtdb.firebaseio.com',
    storageBucket: 'demo1-527bc.appspot.com',
    measurementId: 'G-JG6H4487WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJtPr3NbIBgiiNjydMoFqvhJrYjhCfsko',
    appId: '1:365129109511:android:70c3543a1b8dd269299aa2',
    messagingSenderId: '365129109511',
    projectId: 'demo1-527bc',
    databaseURL: 'https://demo1-527bc-default-rtdb.firebaseio.com',
    storageBucket: 'demo1-527bc.appspot.com',
  );
}
